[package]
name = "ktor-impersonate"
version = "1.0.0"
edition = "2021"
publish = false

[lib]
name = "ktorimpersonate"
crate-type = ["cdylib"]

[dependencies]
jni = "0.21.1"
log = "0.4.22"

[target.'cfg(target_os = "android")'.dependencies]
android_log = "0.1.3"
